version: '3.4'

services:
  queueManagmen:
    image: bohir/queuemanagment
    build:
      context: .
      dockerfile: src/API/Dockerfile
    environment:
      - "UseInMemoryDatabase=false"
      - "ASPNETCORE_ENVIRONMENT=Development"      
      - "ConnectionStrings__DefaultConnection=User ID=queueUser;Password=queuePass;Host=db;Port=5432;Database=queueManagment;Pooling=true;"
      - "IdentityServer__Key__Type=Development"
      - "ASPNETCORE_URLS=http://+:4300"
    ports:
      - "4300:4300"
    depends_on:
      - db
    restart: on-failure
  db:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: queuePass
      POSTGRES_USER: queueUser

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080